# Generated by Django 5.1.2 on 2024-10-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyservice',
            name='location',
        ),
        migrations.AlterField(
            model_name='emergencyservice',
            name='contact_number',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='emergencyservice',
            name='service_type',
            field=models.CharField(choices=[('Shelter', 'Shelter'), ('Legal Aid', 'Legal Aid'), ('Medical', 'Medical'), ('Helpline', 'Helpline'), ('Police Aid', 'Police Aid')], max_length=100),
        ),
    ]
