# Generated by Django 5.1.2 on 2024-10-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contactmessage_alter_case_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteersEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('locality', models.TextField(max_length=200)),
                ('phone_no', models.CharField(max_length=13)),
            ],
        ),
    ]
